"""Core utilities for spec management."""

from .annotations import AnnotationParser
from .gaps import (
    ContentVerifier,
    DetectorFinding,
    DuplicateDetector,
    EvidenceExtractor,
    FormatComplianceDetector,
    GapElement,
    GapSynthesizer,
    InferredClaimPromotionStrategy,
    ProofChainDetector,
    ProseFragmentInferenceDetector,
    SequenceAnalyzer,
    Severity,
    StructuralHealthDetector,
    UncertaintyDetector,
    UndefinedFunctionDetector,
    UnifiedGapDetector,
    detect_gaps,
    format_gaps_md,
)
from .id_registry import (
    FileUidEntry,
    FileUidRegistry,
    RevisionEntry,
    RevisionRegistry,
)
from .ids import IdValidator
from .library_registry import (
    LibraryEntry,
    LibraryIdAllocator,
    generate_stability_key,
)
from .libs_registry import LibsRegistry
from .pin_registry import PinRegistryIndex
from .provenance import (
    GranularityLevel,
    LineageEdge,
    LineageTable,
    MembershipEvidence,
    ProvenanceTracker,
    SourceLocation,
    TargetLocation,
    TrackedUnit,
    UnitStatus,
    UnitType,
    generate_stamp,
    parse_stamp,
)
from .sections import SectionExtractor

__all__ = [
    "AnnotationParser",
    "ContentVerifier",
    "DetectorFinding",
    "DuplicateDetector",
    "EvidenceExtractor",
    "FileUidEntry",
    "FileUidRegistry",
    "FormatComplianceDetector",
    "GapElement",
    "GapSynthesizer",
    "GranularityLevel",
    "IdValidator",
    "InferredClaimPromotionStrategy",
    "LibraryEntry",
    "LibraryIdAllocator",
    "LibsRegistry",
    "LineageEdge",
    "LineageTable",
    "MembershipEvidence",
    "PinRegistryIndex",
    "ProofChainDetector",
    "ProseFragmentInferenceDetector",
    "ProvenanceTracker",
    "RevisionEntry",
    "RevisionRegistry",
    "SectionExtractor",
    "SequenceAnalyzer",
    "Severity",
    "SourceLocation",
    "StructuralHealthDetector",
    "TargetLocation",
    "TrackedUnit",
    "UncertaintyDetector",
    "UndefinedFunctionDetector",
    "UnifiedGapDetector",
    "UnitStatus",
    "UnitType",
    "detect_gaps",
    "format_gaps_md",
    "generate_stability_key",
    "generate_stamp",
    "parse_stamp",
]
