"""Core utilities for spec management."""

from spec_manager.core.annotations import AnnotationParser
from spec_manager.core.gaps import (
    ContentVerifier,
    DetectorFinding,
    DuplicateDetector,
    EvidenceExtractor,
    FormatComplianceDetector,
    GapElement,
    GapSynthesizer,
    InferredClaimPromotionStrategy,
    ProofChainDetector,
    ProseFragmentInferenceDetector,
    SequenceAnalyzer,
    Severity,
    StructuralHealthDetector,
    UncertaintyDetector,
    UndefinedFunctionDetector,
    UnifiedGapDetector,
    detect_gaps,
    format_gaps_md,
)
from spec_manager.core.ids import IdValidator
from spec_manager.core.intermediate import (
    FileSnapshot,
    IntermediateManager,
    IntermediateState,
)
from spec_manager.core.libs_registry import LibsRegistry
from spec_manager.core.provenance import (
    GranularityLevel,
    LineageEdge,
    LineageTable,
    MembershipEvidence,
    ProvenanceTracker,
    SourceLocation,
    TargetLocation,
    TrackedUnit,
    UnitStatus,
    UnitType,
    generate_stamp,
    parse_stamp,
)
from spec_manager.core.sections import SectionExtractor

__all__ = [
    "AnnotationParser",
    "ContentVerifier",
    "DetectorFinding",
    "DuplicateDetector",
    "EvidenceExtractor",
    "FileSnapshot",
    "FormatComplianceDetector",
    "GapElement",
    "GapSynthesizer",
    "GranularityLevel",
    "IdValidator",
    "InferredClaimPromotionStrategy",
    "IntermediateManager",
    "IntermediateState",
    "LibsRegistry",
    "LineageEdge",
    "LineageTable",
    "MembershipEvidence",
    "ProofChainDetector",
    "ProseFragmentInferenceDetector",
    "ProvenanceTracker",
    "SectionExtractor",
    "SequenceAnalyzer",
    "Severity",
    "SourceLocation",
    "StructuralHealthDetector",
    "TargetLocation",
    "TrackedUnit",
    "UncertaintyDetector",
    "UndefinedFunctionDetector",
    "UnifiedGapDetector",
    "UnitStatus",
    "UnitType",
    "detect_gaps",
    "format_gaps_md",
    "generate_stamp",
    "parse_stamp",
]
