"""Schema definitions for structured agent outputs."""

from .architecture import (
    ArchitectureCandidate,
    ArchitectureComponent,
    ArchitectureProposal,
    ArchitectureSelection,
    ArchitectureTradeoffs,
)
from .architecture_brief import ArchitectureBrief
from .atoms import LineAtom
from .edge_list import (
    EdgeListSchema,
    EdgeSchema,
    InterfaceIndexSchema,
    allocate_edge_id,
    build_interface_index,
    read_edge_list_json,
    read_interface_index_json,
    validate_edge_references,
    write_edge_list_json,
    write_interface_index_json,
)
from .evidence_mapper import EvidenceMapperOutput
from .files import FileManifestEntry, FilesManifest
from .gap_judge import GapFinding, GapJudgeOutput
from .interface_contract import (
    ConsumedInterface,
    DataContract,
    InterfaceContractSchema,
    OperationalContract,
    ProvidedInterface,
    read_interface_contract_json,
    validate_contract_references,
    write_interface_contract_json,
    write_interface_contract_markdown,
)
from .library_labels import LibraryLabel, LibraryLabelerOutput
from .qa_judge import QaCriterionResult, QaJudgeOutput
from .review_actions import (
    ReviewAction,
    ReviewActionsReport,
    allocate_action_id,
    generate_stable_action_ids,
    read_review_actions_json,
    validate_pointer_format,
    validate_pointer_references,
    write_review_actions_json,
    write_review_actions_markdown,
)
from .sections import FileSections, SectionSpan
from .spec_indexes import Decision, DecisionsIndex, SpecElement, SpecIndex
from .spec_patches import SpecPatchOp, SpecPatchOutput
from .tasks import (
    GAP_ID_RE,
    TASK_ID_RE,
    PatchGraphSchema,
    TaskCoversSchema,
    TaskIndexEntrySchema,
    TaskIndexSchema,
    TaskSchema,
    TaskStatusSchema,
    read_patch_graph_json,
    read_task_index_json,
    read_task_json,
    read_task_status_json,
    validate_acceptance_criteria,
    validate_decision_gap_coverage,
    validate_edge_coverage,
    validate_element_coverage,
    validate_patch_graph_acyclic,
    write_patch_graph_json,
    write_task_index_json,
    write_task_index_markdown,
    write_task_json,
    write_task_markdown,
    write_task_status_json,
)
from .terms import FileTerms, SectionTerms

__all__ = [
    "GAP_ID_RE",
    "TASK_ID_RE",
    "ArchitectureBrief",
    "ArchitectureCandidate",
    "ArchitectureComponent",
    "ArchitectureProposal",
    "ArchitectureSelection",
    "ArchitectureTradeoffs",
    "ConsumedInterface",
    "DataContract",
    "Decision",
    "DecisionsIndex",
    "EdgeListSchema",
    "EdgeSchema",
    "EvidenceMapperOutput",
    "FileManifestEntry",
    "FileSections",
    "FileTerms",
    "FilesManifest",
    "GapFinding",
    "GapJudgeOutput",
    "InterfaceContractSchema",
    "InterfaceIndexSchema",
    "LibraryLabel",
    "LibraryLabelerOutput",
    "LineAtom",
    "OperationalContract",
    "PatchGraphSchema",
    "ProvidedInterface",
    "QaCriterionResult",
    "QaJudgeOutput",
    "ReviewAction",
    "ReviewActionsReport",
    "SectionSpan",
    "SectionTerms",
    "SpecElement",
    "SpecIndex",
    "SpecPatchOp",
    "SpecPatchOutput",
    "TaskCoversSchema",
    "TaskIndexEntrySchema",
    "TaskIndexSchema",
    "TaskSchema",
    "TaskStatusSchema",
    "allocate_action_id",
    "allocate_edge_id",
    "build_interface_index",
    "generate_stable_action_ids",
    "read_edge_list_json",
    "read_interface_contract_json",
    "read_interface_index_json",
    "read_patch_graph_json",
    "read_review_actions_json",
    "read_task_index_json",
    "read_task_json",
    "read_task_status_json",
    "validate_acceptance_criteria",
    "validate_contract_references",
    "validate_decision_gap_coverage",
    "validate_edge_coverage",
    "validate_edge_references",
    "validate_element_coverage",
    "validate_patch_graph_acyclic",
    "validate_pointer_format",
    "validate_pointer_references",
    "write_edge_list_json",
    "write_interface_contract_json",
    "write_interface_contract_markdown",
    "write_interface_index_json",
    "write_patch_graph_json",
    "write_review_actions_json",
    "write_review_actions_markdown",
    "write_task_index_json",
    "write_task_index_markdown",
    "write_task_json",
    "write_task_markdown",
    "write_task_status_json",
]
