"""Schema definitions for structured agent outputs."""

from .architecture import (
    ArchitectureCandidate,
    ArchitectureComponent,
    ArchitectureProposal,
    ArchitectureSelection,
    ArchitectureTradeoffs,
)
from .architecture_brief import ArchitectureBrief
from .atoms import LineAtom
from .derived_elements import (
    DerivedElement,
    DerivedElementKind,
    ElementStatus,
    RelationEdge,
    RelationType,
    allocate_element_id,
)
from .edge_list import (
    EdgeListSchema,
    EdgeSchema,
    InterfaceIndexSchema,
    allocate_edge_id,
    build_interface_index,
    read_edge_list_json,
    read_interface_index_json,
    validate_edge_references,
    write_edge_list_json,
    write_interface_index_json,
)
from .entities import (
    EntitiesArtifact,
    Entity,
    EntityKind,
    EntityMention,
    EntityTag,
    allocate_entity_id,
)
from .evid_citation import (
    EvidCitation,
    build_evid,
    extract_evid_citations,
    format_evid_citation,
    parse_evid_citation,
    validate_evid_format,
)
from .evidence_graph import (
    EdgeType,
    EvidenceGraph,
    EvidenceGraphEdge,
    EvidenceGraphNode,
    NodeType,
)
from .evidence_mapper import EvidenceMapperOutput
from .evidence_ranges import (
    EVID_CITATION_PATTERN,
    EVIDENCE_ID_PATTERN,
    EvidenceRange,
    EvidenceRangesArtifact,
)
from .files import FileManifestEntry, FilesManifest
from .gap_judge import GapFinding, GapJudgeOutput
from .interface_contract import (
    ConsumedInterface,
    DataContract,
    InterfaceContractSchema,
    OperationalContract,
    ProvidedInterface,
    read_interface_contract_json,
    validate_contract_references,
    write_interface_contract_json,
    write_interface_contract_markdown,
)
from .library_labels import LibraryLabel, LibraryLabelerOutput
from .patch_output import PatchOutputSchema, read_patch_output_json, write_patch_output_json
from .pin_functions import (
    ImportEdge,
    MicroAddress,
    PinFunction,
    PinFunctionRegistry,
    ProjectionType,
)
from .qa_judge import QaCriterionResult, QaJudgeOutput
from .review_actions import (
    ReviewAction,
    ReviewActionsReport,
    allocate_action_id,
    generate_stable_action_ids,
    read_review_actions_json,
    validate_pointer_format,
    validate_pointer_references,
    write_review_actions_json,
    write_review_actions_markdown,
)
from .sections import FileSections, SectionSpan
from .spec_index_v2 import (
    Library,
    SpecIndexV2,
    build_spec_index,
    convert_legacy_spec_index,
)
from .spec_indexes import Decision, DecisionsIndex, SpecElement, SpecIndex
from .spec_patches import SpecPatchOp, SpecPatchOutput
from .tag_delta import (
    TagIndexDelta,
    TagItem,
    TagRelation,
)
from .task_status import (
    AuditResultSchema,
    TaskImplementationStatusSchema,
    TestResultSchema,
    read_task_implementation_status_json,
    validate_status_transition,
    write_task_implementation_status_json,
)
from .tasks import (
    PatchGraphSchema,
    TaskCoversSchema,
    TaskIndexEntrySchema,
    TaskIndexSchema,
    TaskSchema,
    TaskStatusSchema,
    read_patch_graph_json,
    read_task_index_json,
    read_task_json,
    read_task_status_json,
    validate_acceptance_criteria,
    validate_decision_gap_coverage,
    validate_edge_coverage,
    validate_element_coverage,
    validate_patch_graph_acyclic,
    write_patch_graph_json,
    write_task_index_json,
    write_task_index_markdown,
    write_task_json,
    write_task_markdown,
    write_task_status_json,
)
from .terms import FileTerms, SectionTerms

__all__ = [
    "EVIDENCE_ID_PATTERN",
    "EVID_CITATION_PATTERN",
    "ArchitectureBrief",
    "ArchitectureCandidate",
    "ArchitectureComponent",
    "ArchitectureProposal",
    "ArchitectureSelection",
    "ArchitectureTradeoffs",
    "AuditResultSchema",
    "ConsumedInterface",
    "DataContract",
    "Decision",
    "DecisionsIndex",
    "DerivedElement",
    "DerivedElementKind",
    "EdgeListSchema",
    "EdgeSchema",
    "EdgeType",
    "ElementStatus",
    "EntitiesArtifact",
    "Entity",
    "EntityKind",
    "EntityMention",
    "EntityTag",
    "EvidCitation",
    "EvidenceGraph",
    "EvidenceGraphEdge",
    "EvidenceGraphNode",
    "EvidenceMapperOutput",
    "EvidenceRange",
    "EvidenceRangesArtifact",
    "FileManifestEntry",
    "FileSections",
    "FileTerms",
    "FilesManifest",
    "GapFinding",
    "GapJudgeOutput",
    "ImportEdge",
    "InterfaceContractSchema",
    "InterfaceIndexSchema",
    "Library",
    "LibraryLabel",
    "LibraryLabelerOutput",
    "LineAtom",
    "MicroAddress",
    "NodeType",
    "OperationalContract",
    "PatchGraphSchema",
    "PatchOutputSchema",
    "PinFunction",
    "PinFunctionRegistry",
    "ProjectionType",
    "ProvidedInterface",
    "QaCriterionResult",
    "QaJudgeOutput",
    "RelationEdge",
    "RelationType",
    "ReviewAction",
    "ReviewActionsReport",
    "SectionSpan",
    "SectionTerms",
    "SpecElement",
    "SpecIndex",
    "SpecIndexV2",
    "SpecPatchOp",
    "SpecPatchOutput",
    "TagIndexDelta",
    "TagItem",
    "TagRelation",
    "TaskCoversSchema",
    "TaskImplementationStatusSchema",
    "TaskIndexEntrySchema",
    "TaskIndexSchema",
    "TaskSchema",
    "TaskStatusSchema",
    "TestResultSchema",
    "allocate_action_id",
    "allocate_edge_id",
    "allocate_element_id",
    "allocate_entity_id",
    "build_evid",
    "build_interface_index",
    "build_spec_index",
    "convert_legacy_spec_index",
    "extract_evid_citations",
    "format_evid_citation",
    "generate_stable_action_ids",
    "parse_evid_citation",
    "read_edge_list_json",
    "read_interface_contract_json",
    "read_interface_index_json",
    "read_patch_graph_json",
    "read_patch_output_json",
    "read_review_actions_json",
    "read_task_implementation_status_json",
    "read_task_index_json",
    "read_task_json",
    "read_task_status_json",
    "validate_acceptance_criteria",
    "validate_contract_references",
    "validate_decision_gap_coverage",
    "validate_edge_coverage",
    "validate_edge_references",
    "validate_element_coverage",
    "validate_evid_format",
    "validate_patch_graph_acyclic",
    "validate_pointer_format",
    "validate_pointer_references",
    "validate_status_transition",
    "write_edge_list_json",
    "write_interface_contract_json",
    "write_interface_contract_markdown",
    "write_interface_index_json",
    "write_patch_graph_json",
    "write_patch_output_json",
    "write_review_actions_json",
    "write_review_actions_markdown",
    "write_task_implementation_status_json",
    "write_task_index_json",
    "write_task_index_markdown",
    "write_task_json",
    "write_task_markdown",
    "write_task_status_json",
]
