"""JUnit XML parser for test result extraction.

This module parses JUnit XML files generated by pytest to extract test results
including test names, status (passed/failed/error/skipped), duration, and failure details.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


@dataclass
class TestResult:
    """A single test result from JUnit XML."""

    test_name: str
    status: str  # 'passed', 'failed', 'error', 'skipped'
    duration: float  # seconds
    message: str | None = None
    traceback: str | None = None
    classname: str | None = None


@dataclass
class TestSummary:
    """Summary of test results."""

    total: int
    passed: int
    failed: int
    errors: int
    skipped: int


def parse_junit_xml(xml_path: Path) -> tuple[list[TestResult], TestSummary]:
    """Parse JUnit XML file and extract test results.

    The JUnit XML format structure:
    - <testsuites> or <testsuite> root element
    - <testcase name="..." classname="..." time="..."> child elements
    - <failure message="...">traceback</failure> for failed tests
    - <error message="...">traceback</error> for errored tests
    - <skipped> for skipped tests
    - No child element means passed test

    Args:
        xml_path: Path to the JUnit XML file

    Returns:
        Tuple of (list of TestResult objects, TestSummary object)

    Raises:
        FileNotFoundError: If the XML file doesn't exist
        ET.ParseError: If the XML is malformed
    """
    if not xml_path.exists():
        msg = f"JUnit XML file not found: {xml_path}"
        raise FileNotFoundError(msg)

    tree = ET.parse(xml_path)  # noqa: S314
    root = tree.getroot()

    # Handle both <testsuites> and <testsuite> root elements
    if root.tag == "testsuites":
        testsuites = root.findall("testsuite")
    elif root.tag == "testsuite":
        testsuites = [root]
    else:
        msg = f"Unexpected root element: {root.tag}, expected 'testsuites' or 'testsuite'"
        raise ValueError(msg)

    results: list[TestResult] = []
    total = 0
    passed = 0
    failed = 0
    errors = 0
    skipped = 0

    for testsuite in testsuites:
        for testcase in testsuite.findall("testcase"):
            total += 1

            # Extract basic info
            name = testcase.get("name", "")
            classname = testcase.get("classname", "")
            time_str = testcase.get("time", "0")
            try:
                duration = float(time_str)
            except ValueError:
                duration = 0.0

            # Build full test name (classname::test_name format)
            if classname:
                # Convert pytest classname format (e.g., "tests.unit.test_main")
                # to path format (e.g., "tests/unit/test_main.py")
                class_path = classname.replace(".", "/")
                if not class_path.endswith(".py"):
                    class_path += ".py"
                full_name = f"{class_path}::{name}"
            else:
                full_name = name

            # Determine status by checking child elements
            failure = testcase.find("failure")
            error = testcase.find("error")
            skip = testcase.find("skipped")

            if failure is not None:
                # Test failed
                status = "failed"
                message = failure.get("message", "")
                traceback = failure.text or ""
                failed += 1
            elif error is not None:
                # Test errored
                status = "error"
                message = error.get("message", "")
                traceback = error.text or ""
                errors += 1
            elif skip is not None:
                # Test skipped
                status = "skipped"
                message = skip.get("message", "")
                traceback = None
                skipped += 1
            else:
                # Test passed
                status = "passed"
                message = None
                traceback = None
                passed += 1

            results.append(
                TestResult(
                    test_name=full_name,
                    status=status,
                    duration=duration,
                    message=message,
                    traceback=traceback,
                    classname=classname,
                )
            )

    summary = TestSummary(
        total=total,
        passed=passed,
        failed=failed,
        errors=errors,
        skipped=skipped,
    )

    return results, summary
