"""Generate LLM-friendly coverage gap reports via `uv run llm-coverage-report`.

This module integrates with the tier-based coverage system to provide:
- Per-function coverage gaps (functions below threshold)
- Line/branch coverage gaps with source context
- Use-case coverage gaps from the registry
- Tier-specific coverage information (unit, component, integration, e2e, scripts)
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import sys
import textwrap
import traceback
from collections import defaultdict
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml  # Requires PyYAML; already in your dependencies.

from scripts.dev.test_runner.redundant_test_detector import (
    RedundantTestResult,
    detect_redundant_tests,
)


def _debug_enabled() -> bool:
    """Check if debug output is enabled via environment variables."""
    debug_value = os.getenv("DEBUG") or os.getenv("VERBOSE")
    return bool(debug_value and debug_value.lower() in {"1", "true", "yes", "on"})


# Default coverage thresholds (same as test_coverage.py)
DEFAULT_MIN_LINE_COVERAGE = 80.0
DEFAULT_MIN_BRANCH_COVERAGE = 80.0

# Service layer path for component tests
SERVICE_LAYER_PATH = "app/services"


@dataclass
class MissingLineDetail:
    """Details about a missing line of coverage."""

    file: str
    line_number: int
    content: str
    context_before: list[dict[str, Any]]
    context_after: list[dict[str, Any]]
    missing_branch_exits: list[int]


@dataclass
class MissingBranchDetail:
    """Details about a missing branch of coverage."""

    file: str
    source_line: int
    dest_line: int
    source_content: str
    dest_content: str


@dataclass
class FunctionCoverageGap:
    """Details about a function with coverage below threshold."""

    file: str
    function_name: str
    start_line: int
    end_line: int
    line_coverage_pct: float
    branch_coverage_pct: float
    missing_lines: list[int]
    missing_branches: list[tuple[int, int]]
    tier: str
    threshold: float


def _load_coverage_json(path: Path) -> dict[str, Any]:
    """Load coverage JSON produced by coverage.py's JSON reporter.

    Works with:
      - Plain coverage.json from `coverage json` / `--cov-report=json`
      - Wrapped forms like {"raw_data": {...}} used by some tooling.
    """
    if not path.exists():
        raise SystemExit(
            f"Coverage JSON not found at {path!s}. "
            "Generate it with pytest --cov and --cov-report=json:coverage.json "
            "(optionally also --cov-branch for branch coverage)."
        )

    with path.open("r", encoding="utf-8") as f:
        raw = json.load(f)

    # Support both plain coverage.json and wrappers like {"raw_data": {...}}
    if isinstance(raw, dict) and "raw_data" in raw and "files" in raw["raw_data"]:
        data = raw["raw_data"]
    else:
        data = raw

    if "files" not in data:
        raise SystemExit(
            f"Coverage JSON at {path!s} does not contain a 'files' section. "
            "Ensure it was generated by coverage.py's JSON reporter."
        )
    return data  # type: ignore[no-any-return]


def _load_tier_coverage_report(path: Path) -> dict[str, Any] | None:
    """Load the tier-based coverage report from test_coverage.py.

    This is the JSON report generated by `uv run test-coverage --json-report`.
    """
    if not path.exists():
        return None

    with path.open("r", encoding="utf-8") as f:
        return json.load(f)  # type: ignore[no-any-return]


def _read_source_lines(repo_root: Path, filename: str) -> list[str] | None:
    """Read source lines from a file."""
    file_path = (repo_root / filename).resolve()
    try:
        text = file_path.read_text(encoding="utf-8")
    except OSError:
        return None
    return text.splitlines()


def _build_context(
    lines: list[str],
    lineno: int,
    radius: int,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Build context lines before and after a given line number."""
    before: list[dict[str, Any]] = []
    after: list[dict[str, Any]] = []
    total = len(lines)
    start = max(1, lineno - radius)
    end = min(total, lineno + radius)

    for n in range(start, lineno):
        before.append({"line_number": n, "content": lines[n - 1]})
    for n in range(lineno + 1, end + 1):
        after.append({"line_number": n, "content": lines[n - 1]})
    return before, after


def _get_class_field_lines(file_path: Path) -> set[int]:
    """Get line numbers that are class field definitions.

    These are lines inside class bodies that are type annotations (field definitions).
    """
    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(file_path))
    except (SyntaxError, OSError):
        return set()

    class_field_lines: set[int] = set()

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            for item in node.body:
                # AnnAssign is a type-annotated assignment: field: Type = value
                if isinstance(item, ast.AnnAssign):
                    class_field_lines.add(item.lineno)

    return class_field_lines


def _extract_functions_from_file(file_path: Path) -> list[tuple[str, int, int, bool]]:
    """Extract function definitions from a Python file.

    Returns list of (function_name, start_line, end_line, is_method) tuples.
    """
    try:
        source = file_path.read_text(encoding="utf-8")
        tree = ast.parse(source, filename=str(file_path))
    except (SyntaxError, OSError):
        return []

    functions: list[tuple[str, int, int, bool]] = []

    class FunctionVisitor(ast.NodeVisitor):
        def __init__(self) -> None:
            self.in_class = False

        def visit_ClassDef(self, node: ast.ClassDef) -> None:
            old_in_class = self.in_class
            self.in_class = True
            self.generic_visit(node)
            self.in_class = old_in_class

        def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
            self._process_function(node)
            self.generic_visit(node)

        def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
            self._process_function(node)
            self.generic_visit(node)

        def _process_function(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> None:
            start = node.lineno
            end = start
            for child in ast.walk(node):
                if hasattr(child, "lineno"):
                    end = max(end, child.lineno)
            functions.append((node.name, start, end, self.in_class))

    visitor = FunctionVisitor()
    visitor.visit(tree)

    return functions


def _is_private_function(func_name: str) -> bool:
    """Check if a function name indicates a private function."""
    if not func_name.startswith("_"):
        return False
    return func_name not in ("__init__", "__call__")


def _is_in_service_layer(file_path: str) -> bool:
    """Check if a file is in the service layer."""
    return file_path.startswith(SERVICE_LAYER_PATH)


def _calculate_function_coverage_gaps(
    coverage_data: Mapping[str, Any],
    repo_root: Path,
    tier: str,
    min_line: float,
    min_branch: float,
    skip_private: bool = False,
    service_layer_only: bool = False,
) -> list[FunctionCoverageGap]:
    """Calculate per-function coverage and identify gaps below threshold."""
    files: Mapping[str, Any] = coverage_data.get("files", {})
    gaps: list[FunctionCoverageGap] = []

    for filename, file_data_any in files.items():
        # For service-layer-only mode, skip non-service files
        if service_layer_only and not _is_in_service_layer(filename):
            continue

        file_data: Mapping[str, Any] = file_data_any
        abs_path = repo_root / filename

        if not abs_path.exists():
            continue

        executed_lines = set(file_data.get("executed_lines", []))
        missing_lines = set(file_data.get("missing_lines", []))
        missing_branches_raw = file_data.get("missing_branches", []) or []

        # Get class field lines to exclude
        class_field_lines = _get_class_field_lines(abs_path)

        # Remove class field lines from coverage calculation
        executed_lines -= class_field_lines
        missing_lines -= class_field_lines

        # Build branch coverage mapping
        branch_map: dict[int, list[int]] = {}
        for arc in missing_branches_raw:
            if isinstance(arc, (list, tuple)) and len(arc) == 2:
                src, dst = int(arc[0]), int(arc[1])
                if src not in class_field_lines:
                    branch_map.setdefault(src, []).append(dst)

        functions = _extract_functions_from_file(abs_path)

        for func_name, start, end, _is_method in functions:
            # Skip private functions if configured
            if skip_private and _is_private_function(func_name):
                continue

            func_lines = set(range(start, end + 1))
            func_lines -= class_field_lines

            # Calculate line coverage
            func_executed = executed_lines & func_lines
            func_missing = missing_lines & func_lines
            total_relevant = len(func_executed) + len(func_missing)
            line_pct = 100.0 if total_relevant == 0 else (len(func_executed) / total_relevant) * 100

            # Calculate branch coverage
            func_missing_branches: list[tuple[int, int]] = []
            for src, dests in branch_map.items():
                if start <= src <= end:
                    for dst in dests:
                        func_missing_branches.append((src, dst))

            total_branches = len(func_missing_branches) * 2 if func_missing_branches else 0
            covered_branches = total_branches - len(func_missing_branches)
            branch_pct = 100.0 if total_branches == 0 else (covered_branches / total_branches) * 100

            # Check if function is below threshold
            is_below_line = line_pct < min_line
            is_below_branch = branch_pct < min_branch and func_missing_branches

            if is_below_line or is_below_branch:
                gaps.append(
                    FunctionCoverageGap(
                        file=filename,
                        function_name=func_name,
                        start_line=start,
                        end_line=end,
                        line_coverage_pct=line_pct,
                        branch_coverage_pct=branch_pct,
                        missing_lines=sorted(func_missing),
                        missing_branches=func_missing_branches,
                        tier=tier,
                        threshold=min_line,
                    )
                )

    return gaps


def _collect_code_gaps(
    coverage_data: Mapping[str, Any],
    repo_root: Path,
    context_radius: int,
) -> dict[str, Any]:
    """Collect code coverage gaps (missing lines and branches with context)."""
    files: Mapping[str, Any] = coverage_data.get("files", {})
    meta: Mapping[str, Any] = coverage_data.get("meta", {})
    totals: Mapping[str, Any] = coverage_data.get("totals", {})

    missing_lines_details: list[MissingLineDetail] = []
    missing_branch_details: list[MissingBranchDetail] = []

    for filename, file_data_any in files.items():
        file_data: Mapping[str, Any] = file_data_any
        missing_lines: list[int] = list(file_data.get("missing_lines", []))
        missing_branches_raw = file_data.get("missing_branches", []) or []

        source_lines = _read_source_lines(repo_root, filename)

        # Group missing branch arcs by source line
        branch_exits_by_source: dict[int, list[int]] = defaultdict(list)
        for arc in missing_branches_raw:
            if not isinstance(arc, (list, tuple)) or len(arc) != 2:
                continue
            src, dst = int(arc[0]), int(arc[1])
            branch_exits_by_source[src].append(dst)

        if source_lines is None:
            # Still record branch gaps without source text
            for arc in missing_branches_raw:
                if not isinstance(arc, (list, tuple)) or len(arc) != 2:
                    continue
                src, dst = int(arc[0]), int(arc[1])
                missing_branch_details.append(
                    MissingBranchDetail(
                        file=filename,
                        source_line=src,
                        dest_line=dst,
                        source_content="",
                        dest_content="",
                    )
                )
            continue

        # Line-level gaps
        for lineno in sorted(missing_lines):
            if lineno < 1 or lineno > len(source_lines):
                content = ""
                before: list[dict[str, Any]] = []
                after: list[dict[str, Any]] = []
            else:
                content = source_lines[lineno - 1]
                before, after = _build_context(source_lines, lineno, context_radius)

            missing_line_detail = MissingLineDetail(
                file=filename,
                line_number=lineno,
                content=content,
                context_before=before,
                context_after=after,
                missing_branch_exits=sorted(set(branch_exits_by_source.get(lineno, []))),
            )
            missing_lines_details.append(missing_line_detail)

        # Branch-level gaps
        for src, dests in branch_exits_by_source.items():
            for dst in sorted(set(dests)):
                src_content = source_lines[src - 1] if 1 <= src <= len(source_lines) else ""
                dest_content = source_lines[dst - 1] if 1 <= dst <= len(source_lines) else ""
                missing_branch_details.append(
                    MissingBranchDetail(
                        file=filename,
                        source_line=src,
                        dest_line=dst,
                        source_content=src_content,
                        dest_content=dest_content,
                    )
                )

    return {
        "coverage_meta": dict(meta),
        "coverage_totals": dict(totals),
        "missing_lines": [
            {
                "file": m.file,
                "line_number": m.line_number,
                "content": m.content,
                "context_before": m.context_before,
                "context_after": m.context_after,
                "missing_branch_exits": m.missing_branch_exits,
            }
            for m in missing_lines_details
        ],
        "missing_branches": [
            {
                "file": b.file,
                "source_line": b.source_line,
                "dest_line": b.dest_line,
                "source_content": b.source_content,
                "dest_content": b.dest_content,
            }
            for b in missing_branch_details
        ],
    }


class _UsecaseMarkerVisitor(ast.NodeVisitor):
    """AST visitor that collects pytest.mark.usecase("UC-...") markers."""

    def __init__(self, rel_path: str) -> None:
        self.rel_path = rel_path
        self.found: dict[str, list[dict[str, str]]] = defaultdict(list)

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self._visit_test_node(node)
        self.generic_visit(node)

    def visit_AsyncFunctionDef(
        self,
        node: ast.AsyncFunctionDef,
    ) -> None:
        self._visit_test_node(node)
        self.generic_visit(node)

    def _visit_test_node(self, node: ast.AST) -> None:
        func_name = getattr(node, "name", "<unknown>")
        decorators = getattr(node, "decorator_list", [])
        for dec in decorators:
            uc_ids = self._extract_usecase_ids(dec)
            for uc_id in uc_ids:
                self.found[uc_id].append(
                    {
                        "file": self.rel_path,
                        "test_function": func_name,
                    }
                )

    @staticmethod
    def _extract_usecase_ids(dec: ast.AST) -> list[str]:
        if not isinstance(dec, ast.Call):
            return []

        func = dec.func
        func_name = ""
        if isinstance(func, ast.Attribute):
            parts: list[str] = []
            cur: ast.AST | None = func
            while isinstance(cur, ast.Attribute):
                parts.append(cur.attr)
                cur = cur.value
            if isinstance(cur, ast.Name):
                parts.append(cur.id)
            func_name = ".".join(reversed(parts))
        elif isinstance(func, ast.Name):
            func_name = func.id

        if not func_name.endswith("usecase"):
            return []

        uc_ids: list[str] = []
        for arg in dec.args:
            if (
                isinstance(arg, ast.Constant)
                and isinstance(arg.value, str)
                and arg.value.startswith("UC-")
            ):
                uc_ids.append(arg.value)

        for kw in dec.keywords:
            if (
                kw.arg == "id"
                and isinstance(kw.value, ast.Constant)
                and isinstance(kw.value.value, str)
                and kw.value.value.startswith("UC-")
            ):
                uc_ids.append(kw.value.value)

        return uc_ids


def _scan_tests_for_usecases(
    repo_root: Path,
    tests_roots: Sequence[str],
) -> dict[str, list[dict[str, str]]]:
    """Walk test files and collect all use-case markers by id."""
    usecase_to_tests: dict[str, list[dict[str, str]]] = defaultdict(list)

    for root in tests_roots:
        root_path = (repo_root / root).resolve()
        if not root_path.exists():
            continue

        for py_file in root_path.rglob("*.py"):
            try:
                text = py_file.read_text(encoding="utf-8")
            except OSError:
                continue

            try:
                tree = ast.parse(text, filename=str(py_file))
            except SyntaxError:
                continue

            rel_path = str(py_file.relative_to(repo_root))
            visitor = _UsecaseMarkerVisitor(rel_path)
            visitor.visit(tree)
            for uc_id, occurrences in visitor.found.items():
                usecase_to_tests[uc_id].extend(occurrences)

    return usecase_to_tests


def _load_usecase_registry(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _collect_usecase_gaps(
    repo_root: Path,
    usecase_yaml_path: Path,
    tests_roots: Sequence[str],
) -> dict[str, Any]:
    """Compare use-case registry to tests with pytest.mark.usecase markers."""
    registry = _load_usecase_registry(usecase_yaml_path)
    if not registry:
        return {
            "error": f"use-case registry not found or empty at {usecase_yaml_path}",
            "use_cases": [],
        }

    features: Mapping[str, Any] = registry.get("features", {}) or {}
    all_use_cases: list[dict[str, Any]] = []

    for feature_key, feature_data_any in features.items():
        feature_data: Mapping[str, Any] = feature_data_any
        feature_name = feature_data.get("name", feature_key)
        feature_description = feature_data.get("description", "")
        for uc in feature_data.get("use_cases", []) or []:
            uc_id = uc.get("id")
            if not uc_id:
                continue
            uc_record = {
                "id": uc_id,
                "feature_key": feature_key,
                "feature_name": feature_name,
                "feature_description": feature_description,
                "endpoint": uc.get("endpoint"),
                "method": uc.get("method"),
                "description": uc.get("description"),
                "expected_behavior": uc.get("expected_behavior"),
                "test_tier": uc.get("test_tier", "integration"),
            }
            all_use_cases.append(uc_record)

    usecase_to_tests = _scan_tests_for_usecases(repo_root, tests_roots)

    total_count = len(all_use_cases)
    covered_count = 0
    tier_stats: dict[str, dict[str, Any]] = defaultdict(
        lambda: {
            "total": 0,
            "covered": 0,
            "uncovered": 0,
            "uncovered_ids": [],
        }
    )

    enriched_use_cases: list[dict[str, Any]] = []

    for uc in all_use_cases:
        uc_id = uc["id"]
        tier = uc.get("test_tier", "integration")
        tier_stats[tier]["total"] += 1

        tests = usecase_to_tests.get(uc_id, [])
        is_covered = bool(tests)
        if is_covered:
            covered_count += 1
            tier_stats[tier]["covered"] += 1
        else:
            tier_stats[tier]["uncovered"] += 1
            tier_stats[tier]["uncovered_ids"].append(uc_id)

        enriched_use_cases.append(
            {
                **uc,
                "covered_by_tests": is_covered,
                "tests": tests,
            }
        )

    uncovered_count = total_count - covered_count

    return {
        "metadata": {
            "version": registry.get("version", "unknown"),
            "last_updated": registry.get("last_updated", "unknown"),
            "registry_path": str(usecase_yaml_path),
        },
        "totals": {
            "total_use_cases": total_count,
            "covered_use_cases": covered_count,
            "uncovered_use_cases": uncovered_count,
        },
        "tier_stats": tier_stats,
        "use_cases": enriched_use_cases,
        "uncovered_use_cases": [uc for uc in enriched_use_cases if not uc["covered_by_tests"]],
    }


def _collect_function_coverage_gaps(
    repo_root: Path,
    coverage_files: dict[str, Path],
    min_line: float,
    min_branch: float,
) -> dict[str, Any]:
    """Collect per-function coverage gaps for all tiers."""
    tier_configs = {
        "unit": {"skip_private": False, "service_layer_only": False},
        "component": {"skip_private": True, "service_layer_only": True},
        "scripts": {"skip_private": True, "service_layer_only": False},
    }

    all_gaps: list[dict[str, Any]] = []
    tier_summaries: dict[str, dict[str, Any]] = {}

    for tier, coverage_path in coverage_files.items():
        if tier not in tier_configs:
            continue  # Skip use-case tiers (integration, e2e)

        if not coverage_path.exists():
            tier_summaries[tier] = {"error": f"Coverage file not found: {coverage_path}"}
            continue

        coverage_data = _load_coverage_json(coverage_path)
        config = tier_configs[tier]

        gaps = _calculate_function_coverage_gaps(
            coverage_data,
            repo_root,
            tier,
            min_line,
            min_branch,
            skip_private=config["skip_private"],
            service_layer_only=config["service_layer_only"],
        )

        tier_summaries[tier] = {
            "total_functions_below_threshold": len(gaps),
            "threshold_line": min_line,
            "threshold_branch": min_branch,
        }

        for gap in gaps:
            all_gaps.append(
                {
                    "file": gap.file,
                    "function": gap.function_name,
                    "start_line": gap.start_line,
                    "end_line": gap.end_line,
                    "line_coverage_pct": round(gap.line_coverage_pct, 1),
                    "branch_coverage_pct": round(gap.branch_coverage_pct, 1),
                    "missing_lines": gap.missing_lines,
                    "missing_branches": [
                        {"source": src, "dest": dst} for src, dst in gap.missing_branches
                    ],
                    "tier": gap.tier,
                    "threshold": gap.threshold,
                }
            )

    # Sort by coverage (lowest first)
    all_gaps.sort(key=lambda g: g["line_coverage_pct"])

    return {
        "tier_summaries": tier_summaries,
        "functions_below_threshold": all_gaps,
        "total_functions_below_threshold": len(all_gaps),
    }


def build_llm_coverage_document(
    repo_root: Path,
    coverage_json_path: Path,
    usecase_yaml_path: Path,
    tests_roots: Sequence[str],
    context_radius: int,
    min_line: float = DEFAULT_MIN_LINE_COVERAGE,
    min_branch: float = DEFAULT_MIN_BRANCH_COVERAGE,
    tier_coverage_files: dict[str, Path] | None = None,
    coverage_db_path: Path | None = None,
) -> dict[str, Any]:
    """Build a JSON document combining code coverage gaps and use-case gaps.

    Args:
        repo_root: Repository root path
        coverage_json_path: Path to main coverage.json file
        usecase_yaml_path: Path to use_cases.yaml
        tests_roots: Test directories to scan for use-case markers
        context_radius: Lines of context around missing lines
        min_line: Minimum line coverage threshold
        min_branch: Minimum branch coverage threshold
        tier_coverage_files: Optional dict mapping tier names to coverage files
        coverage_db_path: Optional path to .coverage SQLite database for redundant test detection
    """
    coverage_data = _load_coverage_json(coverage_json_path)
    code_gaps = _collect_code_gaps(coverage_data, repo_root, context_radius)
    usecase_gaps = _collect_usecase_gaps(repo_root, usecase_yaml_path, tests_roots)

    # Build function coverage gaps if tier files are provided
    function_gaps: dict[str, Any] = {}
    if tier_coverage_files:
        function_gaps = _collect_function_coverage_gaps(
            repo_root, tier_coverage_files, min_line, min_branch
        )
    else:
        # Fall back to using the main coverage file for function analysis
        function_gaps = _collect_function_coverage_gaps(
            repo_root,
            {"unit": coverage_json_path},
            min_line,
            min_branch,
        )

    # Detect redundant tests if coverage database is available
    redundant_tests_data: dict[str, Any] = {}
    if coverage_db_path and coverage_db_path.exists():
        result = detect_redundant_tests(coverage_db_path)
        redundant_tests_data = {
            "summary": result.summary,
            "redundant_tests": result.redundant_tests,
            "total_tests_analyzed": result.total_tests,
            "tests_with_unique_coverage": result.tests_with_unique_coverage,
        }
    else:
        redundant_tests_data = {
            "summary": {
                "note": "Redundant test detection requires running tests with --cov-context=test"
            },
            "redundant_tests": [],
        }

    return {
        "generated_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "repo_root": str(repo_root),
        "config": {
            "coverage_json_path": str(coverage_json_path),
            "usecase_yaml_path": str(usecase_yaml_path),
            "tests_roots": list(tests_roots),
            "context_radius": context_radius,
            "min_line_coverage": min_line,
            "min_branch_coverage": min_branch,
        },
        "code_coverage": code_gaps,
        "function_coverage": function_gaps,
        "use_case_coverage": usecase_gaps,
        "redundant_tests": redundant_tests_data,
        "prompting_notes": textwrap.dedent(
            """
            This document is designed for LLM-assisted test generation and maintenance.

            ## Test Tier Coverage Requirements
            - Unit tests: 80% line/branch per function for ALL functions in app/
            - Component tests: 80% line/branch per function for app/services/ only
            - Integration tests: 100% use-case coverage
            - E2E tests: 100% use-case coverage
            - Scripts tests: 80% line/branch per function (skip private functions)

            ## How to Use This Report

            1. **Per-Function Coverage Gaps** (`function_coverage.functions_below_threshold`):
               - Lists all functions below the 80% threshold
               - Prioritize functions with lowest coverage
               - Each entry shows missing lines and branches

            2. **Use-Case Coverage Gaps** (`use_case_coverage.uncovered_use_cases`):
               - Lists scenarios without tests
               - Add tests with @pytest.mark.usecase("UC-XXX-NNN")

            3. **Line/Branch Details** (`code_coverage.missing_lines`):
               - Shows exact lines needing coverage with context
               - Use context_before/context_after to understand code flow

            4. **Redundant Tests** (`redundant_tests.redundant_tests`):
               - Lists tests that add NO unique coverage
               - All lines/branches these tests cover are also covered by other tests
               - These tests can be DELETED without reducing overall coverage
               - Review before deletion to ensure no functional value beyond coverage

            Coverage is calculated PER FUNCTION, not per file. Each function must
            individually meet the threshold.

            ## Test Cleanup Guidelines
            When `redundant_tests` contains entries, consider deleting those tests to
            reduce test suite maintenance burden. A test is redundant if every line
            and branch it covers is also covered by at least one other test.
            """
        ).strip(),
    }


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Generate an LLM-friendly coverage gap report (code + use-cases).",
    )
    parser.add_argument(
        "--coverage-json",
        "-c",
        type=Path,
        default=Path("coverage.json"),
        help="Path to coverage.json generated by pytest-cov / coverage json.",
    )
    parser.add_argument(
        "--tier-report",
        type=Path,
        default=None,
        help="Path to tier coverage report from test_coverage.py --json-report.",
    )
    parser.add_argument(
        "--use-cases",
        "-u",
        type=Path,
        default=None,
        help="Path to use_cases.yaml (defaults to tests/docs/use_cases.yaml).",
    )
    parser.add_argument(
        "--repo-root",
        "-r",
        type=Path,
        default=None,
        help="Repository root (defaults to the parent of this script).",
    )
    parser.add_argument(
        "--tests-root",
        "-t",
        action="append",
        default=None,
        help="Tests roots to scan for pytest.mark.usecase markers.",
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("coverage_llm.json"),
        help="Output JSON file path.",
    )
    parser.add_argument(
        "--context-radius",
        "-n",
        type=int,
        default=2,
        help="Number of surrounding lines of context for missing lines.",
    )
    parser.add_argument(
        "--min-line",
        type=float,
        default=DEFAULT_MIN_LINE_COVERAGE,
        help=f"Minimum line coverage threshold (default: {DEFAULT_MIN_LINE_COVERAGE}%%).",
    )
    parser.add_argument(
        "--min-branch",
        type=float,
        default=DEFAULT_MIN_BRANCH_COVERAGE,
        help=f"Minimum branch coverage threshold (default: {DEFAULT_MIN_BRANCH_COVERAGE}%%).",
    )
    parser.add_argument(
        "--coverage-db",
        type=Path,
        default=None,
        help="Path to .coverage SQLite database for redundant test detection (default: .coverage).",
    )
    return parser.parse_args(argv)


def _guess_repo_root(explicit_repo_root: Path | None) -> Path:
    if explicit_repo_root is not None:
        return explicit_repo_root.resolve()
    here = Path(__file__).resolve()
    # scripts/dev/test_runner/llm_coverage_report.py -> repo root (4 levels up)
    return here.parent.parent.parent.parent


def _load_pytest_testpaths(repo_root: Path) -> list[str] | None:
    """Load pytest testpaths from pyproject.toml if available."""
    pyproject = repo_root / "pyproject.toml"
    if not pyproject.exists():
        return None

    try:
        import tomllib
    except ImportError:
        return None

    try:
        with pyproject.open("rb") as f:
            data = tomllib.load(f)
    except Exception:
        return None

    tool_cfg = data.get("tool", {})
    pytest_section = tool_cfg.get("pytest", {})
    pytest_cfg: dict[str, Any] | None = None

    if isinstance(pytest_section, dict):
        ini_options = pytest_section.get("ini_options")
        pytest_cfg = ini_options if isinstance(ini_options, dict) else pytest_section

    if not isinstance(pytest_cfg, dict):
        return None

    tp = pytest_cfg.get("testpaths")
    if isinstance(tp, list):
        return [str(p) for p in tp]
    if isinstance(tp, str):
        return [tp]
    return None


def _discover_tier_coverage_files(repo_root: Path) -> dict[str, Path]:
    """Discover tier coverage files generated by test_coverage.py."""
    tier_files: dict[str, Path] = {}
    patterns = {
        "unit": "coverage_unit.json",
        "component": "coverage_component.json",
        "scripts": "coverage_scripts.json",
    }

    for tier, filename in patterns.items():
        path = repo_root / filename
        if path.exists():
            tier_files[tier] = path

    return tier_files


def _generate_llm_coverage(argv: Sequence[str] | None = None) -> None:
    """Generate LLM coverage report."""
    args = parse_args(argv)

    repo_root = _guess_repo_root(args.repo_root)
    usecase_yaml_path = args.use_cases or (repo_root / "tests" / "docs" / "use_cases.yaml")

    if args.tests_root:
        tests_roots = list(args.tests_root)
    else:
        tests_roots = _load_pytest_testpaths(repo_root) or [
            "tests",
            "scripts/tests",
        ]

    # Discover tier coverage files
    tier_coverage_files = _discover_tier_coverage_files(repo_root)

    # Determine coverage database path for redundant test detection
    coverage_db_path = args.coverage_db or (repo_root / ".coverage")

    doc = build_llm_coverage_document(
        repo_root=repo_root,
        coverage_json_path=args.coverage_json,
        usecase_yaml_path=usecase_yaml_path,
        tests_roots=tests_roots,
        context_radius=args.context_radius,
        min_line=args.min_line,
        min_branch=args.min_branch,
        tier_coverage_files=tier_coverage_files if tier_coverage_files else None,
        coverage_db_path=coverage_db_path,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)

    print(f"Wrote LLM coverage report to {args.output}")
    print("Top-level keys: " + ", ".join(sorted(doc.keys())))

    # Print summary
    func_gaps = doc.get("function_coverage", {})
    total_funcs = func_gaps.get("total_functions_below_threshold", 0)
    if total_funcs > 0:
        print(f"Functions below threshold: {total_funcs}")

    uc_gaps = doc.get("use_case_coverage", {})
    uncovered_ucs = len(uc_gaps.get("uncovered_use_cases", []))
    if uncovered_ucs > 0:
        print(f"Uncovered use-cases: {uncovered_ucs}")

    # Print redundant test summary
    redundant_data = doc.get("redundant_tests", {})
    redundant_tests = redundant_data.get("redundant_tests", [])
    if redundant_tests:
        print(f"Redundant tests (can be deleted): {len(redundant_tests)}")


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point: delegate LLM coverage report generation and normalize exit codes."""
    # Note: This tool is file-based (reads coverage.json, use_cases.yaml, and test files).
    # No database credentials are required.
    try:
        _generate_llm_coverage(argv)
    except SystemExit as exc:
        code = exc.code if isinstance(exc.code, int) else 1
        raise SystemExit(code) from exc
    except Exception as exc:
        error_message = f"Failed to generate LLM coverage report: {exc}"
        if _debug_enabled():
            print(error_message, file=sys.stderr)
            traceback.print_exc(file=sys.stderr)
        else:
            print(error_message, file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
